#!/bin/bash

options=(
	style=round
	width=5.0
	hidpi=on
	#active_color="gradient(top_left=0xff663399,bottom_right=0xff000000)"
	active_color="gradient(top_left=0xff663399,bottom_right=0xff993366)"
	inactive_color=0x000000
)	

borders "${options[@]}"
